### PR TITLE
Fixed Typo in PlayerInfo comment

### PR DESCRIPTION
**Pull request by fatton139**
Says "intial" when it should say "initial"

### CODE REVIEW

**Comment by fatton139** [comment]
@Assasindie would you be able to take a look when you're free, thanks.

**Comment by AlexB6773** [comment]
Can this be tested?

**Comment by fatton139** [comment]
> Can this be tested?

No, but tooling can help, I'd be happy to look into setup tooling for you in a future enhancement.

I can contact you privately to discuss this further.

**Comment by AlexB6773** [comment]
no thanks

**Pull request merged**
